<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "alm_iconfields"
 *
 * Auto generated by Extension Builder 2015-05-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'IconFields',
	'description' => 'IconFields for page und content.',
	'category' => 'be',
	'author' => 'Andi Platen',
	'author_email' => 'info@wireframe.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'alm_iconpicker' => '0.2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
